config/routes.rb
Rails.application.routes.draw do
  resources :offices
  resources :projects
  get 'welcome/index'

   root 'projects#index'

end

app/models/office.rb
class Office < ActiveRecord::Base
	has_and_belongs_to_many :projects
	validates :city, presence: true
	validates :country, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
	has_and_belongs_to_many :offices
	validates :name, presence: true
	validates :description, presence: true
	validates :status, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: [:show, :edit, :update, :destroy]

  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.all
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: 'Office was successfully created.' }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: 'Office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.require(:office).permit(:city, :country)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    params[:project][:office_ids] ||= []
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :picture, :status, :production, :repository, :management, :email, :technologies, {:office_ids => []}, :documentation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projector</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <nav>
      <div class="nav-wrapper  ">
       <a href="/"><img src="<%= asset_path( 'projector.png' ) %>"  class="icon"/></a> 
        <a href="/" class="brand-logo">   Projector</a>
          
        <div class="right ">
          <%= link_to '<i class="material-icons">add</i>'.html_safe, new_project_path, :class => 'btn-floating btn-large waves-effect waves-light blue-grey darken-4 icon' %>
       </div>
      </div>
    </nav>

  <div class='container'>




    <%= yield %>
  </div>



</body>
</html>

app/views/offices/_form.html.erb
<%= form_for(@office) do |f| %>
  <% if @office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
      <% @office.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="input-field col s12">
      <%= f.label :city %><br>
      <%= f.text_field :city, :class=>'validate', :required => true%>
    </div>
  </div>
  <div class="row">
   <div class="input-field col s12">
      <%= f.label :country %><br>
      <%= f.text_field :country, :class=>'validate', :required => true %>
    </div>
  </div>
  <div class="row">
    <%= f.submit 'Submit', :class => 'btn' %>
    <%= link_to 'Back', offices_path, :class => 'btn' %>
  </div>
<% end %>

app/views/offices/edit.html.erb
<h1>Editing Office</h1>

<%= render 'form' %>

<%= link_to 'Show', @office %> 

app/views/offices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Offices</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offices.each do |office| %>
      <tr>
        <td><%= office.city %></td>
        <td><%= office.country %></td>
        <td><%= link_to 'Show', office %></td>
        <td><%= link_to 'Edit', edit_office_path(office) %></td>
        <td><%= link_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Office', new_office_path %>

app/views/offices/new.html.erb
<h1>New Office</h1>

<%= render 'form' %>

app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @office.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @office.country %>
</p>
<% @office.projects.each do |project| %>
<p><%= project.name %></p>
<% end %>

<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="input-field col s12">
      <%= f.label :name %><br>
      <%= f.text_field :name, :class=>'validate', :required => true %>
    </div> 
  </div>

  <div class="row">
     <div class="input-field col s12">
       <%= f.label :office %><br>
      <% hidden_field_tag "project[office_ids][]", nil %>
      <% Office.all.each do |office|%>
        <p>
        <%= check_box_tag "project[office_ids][]", office.id, @project.offices.include?(office), :id=>"project_#{office.city}"%>
        <%=f.label office.city.titleize %>
        </p>
      <% end %>
      <br>
      <p>Register a <%= link_to 'New Office', new_office_path %></p>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.label :status %><br><br>
      <%= f.select :status, ['In Development', 'Crying for Help', 'Concluded', 'Abandoned']%>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.label :description %><br>
      <%= f.text_area :description, :class=>"materialize-textarea validate", :required => true %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.label :technologies %><br>
      <%= f.text_area :technologies, :class=>"materialize-textarea" %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.label "Link to Production" %><br>
      <%= f.text_field :production %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.label :documentation %><br>
      <%= f.text_field :documentation %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.label "Project Management System Link" %><br>
      <%= f.text_field :management %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.label :repository %><br>
      <%= f.text_field :repository %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
  </div>

  <div class="row">
    <div class="file-field input-field">
      <div class="btn">
        <span>Image</span>

        <%= f.file_field :picture %>
      </div>
    </div>
  </div>



 
  <div class="row">
    <%= f.submit 'Submit', :class => 'btn ' %>
    <%= link_to 'Back', projects_path, :class => 'btn' %>
   
  </div>

<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="input-field col s3">
    <select id="status">
    <%= options_for_select([['All Status', :all],['Crying for Help', :help], ['In Development', :development], ['Concluded', :concluded], ['Abandoned', :abandoned]], :all) %>
 </select>
  </div>
</div>
 
 



<div id="projects">
  <% @projects.in_groups_of(4) do |group|%>
  <div class="row">
    <% group.compact.each do |project| %>
      <div class="col s3">
        <%= link_to project do %> 
          <div class="card" id='project' data-status='<%= project.status%>'>
            <div class="card-ximage" >
              <%= image_tag project.picture_url, width: '100%', :class=>" img-thumbnail activator" if project.present? %>

              <span class="card-title black-text"><%= project.name %></span>
              
     
            </div>
            <div class="card-reveal">
              <span class="card-title black-text"><%= project.name %></span>
              <p>
              <%= project.description %>
              </p>
            </div>
        <% end %> 
          
          </div>
        </a> 
      </div>
    <% end %>
  </div>


<% end %>
</div>






<script src="/assets/filters.js"></script>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
  <div class="col s4">
    <%= image_tag(@project.picture_url, width: '100%', :class => 'img-thumbnail' ) if @project.picture.present? %>
  </div>

  <div class="col s8">


          <div class="card blue-grey lighten-5">
            <div class="card-content">
              <h3><%= @project.name %> </h3>
              
                <p><b>Status: </b><%= @project.status %></p>
                <p><b> <%= 'Offices:' if @project.offices.present? %></b>
                  <% @project.offices.each do |office|%>
                 <span class='chip'> <%= link_to  office.city, office %></span>
                  <% end %></p>
                   <p><b><%= 'Technologies:'if @project.technologies.present? %> </b><%= @project.technologies %></p><br>
                   <p><b><%= 'Description:' if @project.description.present? %> </b><%= @project.description %></p><br>
              
                <p><b><%= 'Project in Production:' if @project.production.present? %> </b><%= link_to @project.production, @project.production, :target => '_blank'  if @project.production.present? %></p>
               <p><b><%= 'Documentation:'if @project.documentation.present? %>  </b><%=link_to @project.documentation,  @project.documentation, :target => '_blank' %></p>
               
               
                <p><b><%= 'Repository:' if @project.repository.present? %> </b><%= link_to @project.repository, @project.repository, :target => '_blank'    %></p>
                <p><b><%= 'Project Management System:'if @project.management.present? %>  </b><%=link_to @project.management, @project.management, :target => '_blank'  %></p>
                  <p><b><%= 'Contact:' if @project.email.present? %> </b><%= @project.email  %></p><br>

                  <div class='right-align'>
                    <%= link_to 'Edit', edit_project_path(@project), :class => 'btn ' %> 
                    <%= link_to 'Destroy', @project, data: { confirm: 'Are you sure?' }, method: :delete, :class => 'btn ' %> 
                    <%= link_to 'Back', projects_path, :class => 'btn ' %>
                  </div>


            </div>
          </div>

           



  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>